### ISSUE TITLE
Сделать систему учета по рекомендации

### ISSUE THREAD

**Issue by dram1008** [dram1008/capitalov#260]
думаю по мылу просто что бы знать кто кого рекомендовал и платить $

**Comment by CAPITALOV** [comment]
https://www.capitalov.com/about Убрать слово О шедевре оно не подходит заменить на "Национальное Агентство Капиталов"

**Comment by dram1008** [comment]
нужно подробности

**Comment by dram1008** [comment]
Сделать реферальную сиситему

**Comment by dram1008** [comment]
- в профиле сделать ссылку
- сделать регистрацию по ссылке
- сделать учет вознаграждений
