### ISSUE TITLE
изменить в шапке браузера название о шедевре

### ISSUE THREAD

**Issue by CAPITALOV** [dram1008/capitalov#271]
![default](https://cloud.githubusercontent.com/assets/14125222/9683849/6daf4d76-531c-11e5-8ad5-10d1db9cae92.JPG)

Национальное Агентство Капиталов - должно быть

**Comment by dram1008** [comment]
Прямо текстом написать?

**Comment by CAPITALOV** [comment]
![default](https://cloud.githubusercontent.com/assets/14125222/9683903/c4db293a-531c-11e5-8b51-5eb1414aeddd.JPG)
 дописать это кто мы

**Comment by CAPITALOV** [comment]
Национальное Агентство Капиталов

**Comment by CAPITALOV** [comment]
в шапке тоже самое как тарифы и регистрация

**Comment by dram1008** [comment]
ничего не понимаю что надо?

**Comment by dram1008** [comment]
а понял

**Comment by dram1008** [comment]
![2015-09-04 15-55-43](https://cloud.githubusercontent.com/assets/8858319/9684001/6e912c0e-531d-11e5-85ab-2b6a2c4b111d.png)
