### ISSUE TITLE
способы оплаты

### ISSUE THREAD

**Issue by CAPITALOV** [dram1008/capitalov#287]
можно разместить логотипы платёжных систем платить легко банк, карты, paypal, яндекс деньги  - с левой стороны от картинки в свободном месте что бы было сразу видно и в тарифах так же
![default](https://cloud.githubusercontent.com/assets/14125222/9694864/2bd0d642-5365-11e5-88b4-5f995d3ce386.JPG)

**Comment by dram1008** [comment]
принял

**Comment by dram1008** [comment]
Нужен Дизайн

**Comment by dram1008** [comment]
https://capitalov.com/price
