### ISSUE TITLE
99$ Базовый Национальный рынок и 249$ "Западный и валютный рынок" 

### ISSUE THREAD

**Issue by CAPITALOV** [dram1008/capitalov#295]
https://capitalov.com/price  изменить цены на психологический уровень восприятия  - 99$ Базовый Национальный рынок и 249$ "Западный и валютный рынок" 

Телефон для обратной связи: +7 499 394-27-43 
National Agency of the Capitals

P.S / Привезти контакт к общему формату принятому в интернете:

**Comment by dram1008** [comment]
https://capitalov.com/price
