### ISSUE TITLE
Графики с бирж не обновляются https://capitalov.com/stock

### ISSUE THREAD

**Issue by CAPITALOV** [dram1008/capitalov#347]
Сбой с обновлением графиков с биржы посмотри котировки все до 8-9 заканчиваются 
"сбер п" сам обновил т.к. там некорректно стало показывать график https://capitalov.com/stock
![default](https://cloud.githubusercontent.com/assets/14125222/9831040/2172d9d0-594f-11e5-9733-f4a1bd522e93.JPG)

**Comment by dram1008** [comment]
поправил
в сервере не тот путь прописал
сделал закачку свеч
